-- ==============================================================================
-- ACADEMIA-INDUSTRY COLLABORATION PORTAL - SEED SCRIPT
-- ==============================================================================

-- Seed Skills taxonomy
INSERT INTO public.skills (name, category, description) VALUES
    ('Python', 'programming_languages', 'Core Python, OOP, data structures, and script automation'),
    ('TypeScript', 'programming_languages', 'Typed superset of JavaScript for scalable application development'),
    ('JavaScript', 'programming_languages', 'Modern ES6+ syntax, asynchronous programming, DOM APIs'),
    ('Java', 'programming_languages', 'Enterprise Java, Spring Boot, OOP design patterns'),
    ('C++', 'programming_languages', 'High-performance computing, memory management, STL'),
    ('Go (Golang)', 'programming_languages', 'Concurrent microservices, goroutines, backend systems'),
    ('Rust', 'programming_languages', 'Memory-safe systems programming and high-throughput networking'),
    ('SQL', 'programming_languages', 'Relational querying, indexing, query optimization, analytics'),
    ('React', 'frameworks_libraries', 'Declarative UI library, hooks, state management, SPA architecture'),
    ('Next.js', 'frameworks_libraries', 'Full-stack React framework with SSR, SSG, Server Actions, App Router'),
    ('Node.js', 'frameworks_libraries', 'Event-driven runtime for backend RESTful and WebSocket servers'),
    ('Express.js', 'frameworks_libraries', 'Minimalist web framework for Node.js API development'),
    ('FastAPI', 'frameworks_libraries', 'Modern high-performance Python web framework with OpenAPI schemas'),
    ('Django', 'frameworks_libraries', 'Batteries-included Python web framework with ORM and security'),
    ('Tailwind CSS', 'frameworks_libraries', 'Utility-first modern CSS design framework'),
    ('PostgreSQL', 'databases', 'Advanced open-source relational database with ACID, RLS, and JSONB'),
    ('MongoDB', 'databases', 'Document-oriented NoSQL database for flexible data modeling'),
    ('Redis', 'databases', 'In-memory key-value cache, pub/sub message broker, session storage'),
    ('Supabase', 'databases', 'Open-source Firebase alternative with PostgreSQL, RLS, Edge Functions'),
    ('Docker', 'cloud_devops', 'Containerization of applications and microservices'),
    ('Kubernetes', 'cloud_devops', 'Container orchestration, scaling, service discovery'),
    ('Amazon Web Services (AWS)', 'cloud_devops', 'Cloud architecture covering EC2, S3, RDS, Lambda'),
    ('Google Cloud Platform (GCP)', 'cloud_devops', 'Cloud infrastructure, BigQuery, Cloud Run, GCS'),
    ('CI/CD Pipelines', 'cloud_devops', 'Automated testing and deployment via GitHub Actions / GitLab CI'),
    ('Terraform', 'cloud_devops', 'Infrastructure as Code (IaC) provisioning'),
    ('PyTorch', 'ai_ml_datascience', 'Deep learning framework for computer vision, NLP, and neural networks'),
    ('TensorFlow', 'ai_ml_datascience', 'End-to-end machine learning platform and model deployment'),
    ('Scikit-Learn', 'ai_ml_datascience', 'Classical machine learning algorithms, clustering, classification'),
    ('Pandas & NumPy', 'ai_ml_datascience', 'High-performance data manipulation, cleaning, and numerical analysis'),
    ('Natural Language Processing (NLP)', 'ai_ml_datascience', 'Text tokenization, sentiment analysis, LLMs, embeddings'),
    ('Computer Vision (OpenCV)', 'ai_ml_datascience', 'Image processing, object detection (YOLO), image segmentation'),
    ('Generative AI & LLMs', 'ai_ml_datascience', 'RAG architectures, prompt engineering, fine-tuning, LangChain'),
    ('Network Security', 'cybersecurity', 'Firewalls, TCP/IP analysis, IDS/IPS, network packet dissection'),
    ('Ethical Hacking & Penetration Testing', 'cybersecurity', 'Vulnerability assessment, OWASP Top 10, exploitation techniques'),
    ('Cryptography', 'cybersecurity', 'Symmetric/asymmetric encryption, hashing, TLS/SSL certificates, PKI'),
    ('System Design', 'core_engineering', 'High-level architectural design, microservices, load balancing, caching'),
    ('Data Structures & Algorithms', 'core_engineering', 'Algorithmic complexity, tree/graph traversal, dynamic programming'),
    ('Embedded Systems & IoT', 'core_engineering', 'Microcontroller programming (ESP32, Arduino), MQTT, sensor integration'),
    ('REST & GraphQL API Design', 'core_engineering', 'Contract-first API architecture, pagination, rate limiting'),
    ('Technical Communication', 'soft_skills', 'Verbal/written documentation, stakeholder presentations, tech talks'),
    ('Agile & Scrum Methodologies', 'soft_skills', 'Sprint planning, backlog grooming, retrospective facilitation'),
    ('Problem Solving & Critical Thinking', 'soft_skills', 'Root cause analysis, debugging heuristics, creative troubleshooting')
ON CONFLICT (name) DO NOTHING;
